//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: PlayerInitData.proto
namespace CarcassonneCraft
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerInitData")]
  public partial class PlayerInitData : global::ProtoBuf.IExtensible
  {
    public PlayerInitData() {}
    
    private string _username;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string username
    {
      get { return _username; }
      set { _username = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _selects = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"selects", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> selects
    {
      get { return _selects; }
    }
  
    private CarcassonneCraft.PlayerSyncData _sync;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"sync", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public CarcassonneCraft.PlayerSyncData sync
    {
      get { return _sync; }
      set { _sync = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OtherPlayerInitData")]
  public partial class OtherPlayerInitData : global::ProtoBuf.IExtensible
  {
    public OtherPlayerInitData() {}
    
    private string _username;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string username
    {
      get { return _username; }
      set { _username = value; }
    }
    private CarcassonneCraft.PlayerSyncData _sync;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"sync", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public CarcassonneCraft.PlayerSyncData sync
    {
      get { return _sync; }
      set { _sync = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerSyncData")]
  public partial class PlayerSyncData : global::ProtoBuf.IExtensible
  {
    public PlayerSyncData() {}
    
    private int _userid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int userid
    {
      get { return _userid; }
      set { _userid = value; }
    }
    private float _xpos;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"xpos", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float xpos
    {
      get { return _xpos; }
      set { _xpos = value; }
    }
    private float _ypos;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"ypos", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float ypos
    {
      get { return _ypos; }
      set { _ypos = value; }
    }
    private float _zpos;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"zpos", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float zpos
    {
      get { return _zpos; }
      set { _zpos = value; }
    }
    private float _xrot;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"xrot", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float xrot
    {
      get { return _xrot; }
      set { _xrot = value; }
    }
    private float _yrot;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"yrot", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float yrot
    {
      get { return _yrot; }
      set { _yrot = value; }
    }
    private int _animestate;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"animestate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int animestate
    {
      get { return _animestate; }
      set { _animestate = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerInitDatas")]
  public partial class PlayerInitDatas : global::ProtoBuf.IExtensible
  {
    public PlayerInitDatas() {}
    
    private CarcassonneCraft.PlayerInitData _player;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public CarcassonneCraft.PlayerInitData player
    {
      get { return _player; }
      set { _player = value; }
    }
    private readonly global::System.Collections.Generic.List<CarcassonneCraft.OtherPlayerInitData> _otherplayers = new global::System.Collections.Generic.List<CarcassonneCraft.OtherPlayerInitData>();
    [global::ProtoBuf.ProtoMember(2, Name=@"otherplayers", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<CarcassonneCraft.OtherPlayerInitData> otherplayers
    {
      get { return _otherplayers; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OtherPlayerInitDatas")]
  public partial class OtherPlayerInitDatas : global::ProtoBuf.IExtensible
  {
    public OtherPlayerInitDatas() {}
    
    private readonly global::System.Collections.Generic.List<CarcassonneCraft.OtherPlayerInitData> _otherplayers = new global::System.Collections.Generic.List<CarcassonneCraft.OtherPlayerInitData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"otherplayers", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<CarcassonneCraft.OtherPlayerInitData> otherplayers
    {
      get { return _otherplayers; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerSyncDatas")]
  public partial class PlayerSyncDatas : global::ProtoBuf.IExtensible
  {
    public PlayerSyncDatas() {}
    
    private readonly global::System.Collections.Generic.List<CarcassonneCraft.PlayerSyncData> _syncs = new global::System.Collections.Generic.List<CarcassonneCraft.PlayerSyncData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"syncs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<CarcassonneCraft.PlayerSyncData> syncs
    {
      get { return _syncs; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}