//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: AreaInfo.proto
namespace CarcassonneCraft
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AreaInfo")]
  public partial class AreaInfo : global::ProtoBuf.IExtensible
  {
    public AreaInfo() {}
    
    private int _areaid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"areaid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int areaid
    {
      get { return _areaid; }
      set { _areaid = value; }
    }
    private string _areaname;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"areaname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string areaname
    {
      get { return _areaname; }
      set { _areaname = value; }
    }
    private int _userid;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"userid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int userid
    {
      get { return _userid; }
      set { _userid = value; }
    }
    private string _username;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string username
    {
      get { return _username; }
      set { _username = value; }
    }
    private int _rating;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"rating", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int rating
    {
      get { return _rating; }
      set { _rating = value; }
    }
    private bool _rated;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"rated", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool rated
    {
      get { return _rated; }
      set { _rated = value; }
    }
    private readonly global::System.Collections.Generic.List<CarcassonneCraft.UserInfo> _editusers = new global::System.Collections.Generic.List<CarcassonneCraft.UserInfo>();
    [global::ProtoBuf.ProtoMember(7, Name=@"editusers", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<CarcassonneCraft.UserInfo> editusers
    {
      get { return _editusers; }
    }
  
    private int _xareasnum;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"xareasnum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int xareasnum
    {
      get { return _xareasnum; }
      set { _xareasnum = value; }
    }
    private int _zareasnum;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"zareasnum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int zareasnum
    {
      get { return _zareasnum; }
      set { _zareasnum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserInfo")]
  public partial class UserInfo : global::ProtoBuf.IExtensible
  {
    public UserInfo() {}
    
    private int _userid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int userid
    {
      get { return _userid; }
      set { _userid = value; }
    }
    private string _username;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string username
    {
      get { return _username; }
      set { _username = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}