//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: PushData.proto
namespace CarcassonneCraft
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PushData")]
  public partial class PushData : global::ProtoBuf.IExtensible
  {
    public PushData() {}
    
    private float _xpos;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"xpos", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float xpos
    {
      get { return _xpos; }
      set { _xpos = value; }
    }
    private float _ypos;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ypos", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float ypos
    {
      get { return _ypos; }
      set { _ypos = value; }
    }
    private float _zpos;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"zpos", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float zpos
    {
      get { return _zpos; }
      set { _zpos = value; }
    }
    private float _xrot;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"xrot", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float xrot
    {
      get { return _xrot; }
      set { _xrot = value; }
    }
    private float _yrot;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"yrot", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float yrot
    {
      get { return _yrot; }
      set { _yrot = value; }
    }
    private int _animestate;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"animestate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int animestate
    {
      get { return _animestate; }
      set { _animestate = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}