//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: RequestForkInfo.proto
namespace CarcassonneCraft
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RequestForkInfo")]
  public partial class RequestForkInfo : global::ProtoBuf.IExtensible
  {
    public RequestForkInfo() {}
    
    private int _areaid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"areaid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int areaid
    {
      get { return _areaid; }
      set { _areaid = value; }
    }
    private string _forkname;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"forkname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string forkname
    {
      get { return _forkname; }
      set { _forkname = value; }
    }
    private int _xareasnum;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"xareasnum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int xareasnum
    {
      get { return _xareasnum; }
      set { _xareasnum = value; }
    }
    private int _zareasnum;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"zareasnum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int zareasnum
    {
      get { return _zareasnum; }
      set { _zareasnum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}