//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: SelectInfo.proto
namespace CarcassonneCraft
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SelectInfo")]
  public partial class SelectInfo : global::ProtoBuf.IExtensible
  {
    public SelectInfo() {}
    
    private int _selectindex;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"selectindex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int selectindex
    {
      get { return _selectindex; }
      set { _selectindex = value; }
    }
    private int _areaid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"areaid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int areaid
    {
      get { return _areaid; }
      set { _areaid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}